name: Release on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - ".github/workflows/release.yaml"



jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Display release info
        run: |
            echo "$Version: {{ steps.query-release-info.outputs.version }}"
            echo "$Date: {{ steps.query-release-info.outputs.release-date }}"
            echo "${{ steps.query-release-info.outputs.release-notes }}"



      - name: Bump changelog version
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: bump
          version: minor

      - name: Display version number
        run: |
          echo "New release version: ${{ steps.update-changelog.outputs.version }}"
