name: Release on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Parse changelog
        id: changelog
        run: |
          auto-changelog --unreleased --stdout
          VERSION=$(auto-changelog)
          NOTES=$(auto-changelog)

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          name: Release v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.notes }}
