name: Release on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - ".github/workflows/release.yaml"

permissions:
  contents: write


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Release
        env:
          VERSION: ${{ steps.query-release-info.outputs.version }}
          RELEASE_DATE: ${{ steps.query-release-info.outputs.release-date }}
          RELEASE_NOTES: ${{ steps.query-release-info.outputs.release-notes }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Version: $VERSION"
            echo "$RELEASE_NOTES" > release_notes.md

            date > date1.txt
            date > date2.txt

            LATEST_RELEASE=$(gh release view --json tagName --jq '.tagName')
            if [ "$VERSION" == "$LATEST_RELEASE" ]; then
                echo "Versions match nothing to do!"
            else
              echo "Release Time!"
              gh release create $VERSION --title "$VERSION" -F release_notes.md *.txt

              # Extract major and major.minor from the version
              MAJOR=$(echo "$VERSION" | cut -d. -f1)
              MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)

              # Update (move) major and major.minor tags to point to the latest release commit
              git tag -f "$MAJOR"
              git tag -f "$MAJOR_MINOR"
              git push origin "$MAJOR" --force
              git push origin "$MAJOR_MINOR" --force
            fi




