name: Release on Changelog Update

on:
  push:
    paths:
      - 'CHANGELOG.md'
      - ".github/workflows/release.yaml"

permissions:
  contents: write


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Release
        env:
          VERSION: ${{ steps.query-release-info.outputs.version }}
          RELEASE_DATE: ${{ steps.query-release-info.outputs.release-date }}
          RELEASE_NOTES: ${{ steps.query-release-info.outputs.release-notes }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "Version: $VERSION"
            echo "$RELEASE_NOTES" > release_notes.md

            date > date1.txt
            date > date2.txt

            gh release create $VERSION --title "Release $VERSION - $RELEASE_DATE" -F release_notes.md *.txt


